root: true
parser: '@typescript-eslint/parser'

env:
  node: true

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-var-requires': 0
  'no-empty': 0
